image: "alpine:latest"

before_script:
  - echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
  - apk add --no-cache crystal g++ gcc go make nodejs-current openjdk11 perl php7 python2 python3 rakudo ruby rust
  - ln -s /usr/lib/jvm/default-jvm/bin/javac /usr/local/bin/javac

benchmark-all:
    script:
        - cd one_million;
        - make
